#!/system/bin/sh

######### IMPORT BOOTKALI INITIALIZATION #########
SCRIPT_PATH=$(readlink -f $0)
. ${SCRIPT_PATH%/*}/bootkali_log
. ${SCRIPT_PATH%/*}/bootkali_init

######### log the time when the script is run #########
[ -d $nhfiles/logs ] || mkdir $nhfiles/logs
echo "$(date +%F_%T) || $(basename $0) is run." >> "$nhfiles/logs/$(date +%F)"

######### EXPORT ENVIRONMENT #########
export bin=/system/bin
export mnt=$mnt
PRESERVED_PATH=$PATH
export PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH
export TERM=linux
export HOME=/root
export USER=root
export LOGNAME=root
unset LD_PRELOAD

######### Custom initial scripts can run here #########
[ ! -f $mnt$HOME/.hushlogin ] && touch $mnt$HOME/.hushlogin

######### TERMINAL SETUP #########
clear
