#!/system/bin/sh

######### IMPORT BOOTKALI INITIALIZATION #########
SCRIPT_PATH=$(readlink -f $0)
. ${SCRIPT_PATH%/*}/bootkali_init

######### EXPORT ENVIRONMENT #########
export bin=/system/bin
export mnt=$mnt
PRESERVED_PATH=$PATH
export PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH
export TERM=linux
export HOME=/root
export USER=root
export LOGNAME=root
unset LD_PRELOAD

######### TERMINAL SETUP #########
# Colors
ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
COL_RED=$ESC_SEQ"31;01m"
COL_GREEN=$ESC_SEQ"32;01m"
COL_YELLOW=$ESC_SEQ"33;01m"
COL_BLUE=$ESC_SEQ"34;01m"
COL_MAGENTA=$ESC_SEQ"35;01m"
COL_CYAN=$ESC_SEQ"36;01m"

clear

# Login Banner (the most important part)
echo -e "$COL_BLUE     __     _   _                 _            "
echo -e "  /\ \ \___| |_| |__  _   _ _ __ | |_ ___ _ __ "
echo -e " /  \/ / _ \ __| '_ \| | | | '_ \| __/ _ \ '__|"
echo -e "/ /\  /  __/ |_| | | | |_| | | | | ||  __/ |   "
echo -e "\_\ \/ \___|\__|_| |_|\__,_|_| |_|\__\___|_|   "
echo -e "$COL_RESET"
echo -e "$COL_CYAN============== KALI LINUX =====================$COL_RESET"
echo -e ""