#!/system/bin/sh

# Script to backup your kali chroot folder as a tar.gz file.

######### IMPORT BOOTKALI INITIALIZATION #########
SCRIPT_PATH=$(readlink -f $0)
. ${SCRIPT_PATH%/*}/bootkali_log

[ ! "`which busybox`" ] && bklog "[-] No busybox is installed, if you did have it installed, please symlink it to /system/bin"

case $# in
2)
	[ ! -d $1 ] && bklog "[-] $1 not found, please check again." && exit 1;
	[ -e $2 ] && bklog "[-] Found existing $2, please rename it first." && exit 1;
	target_dir=`echo "$1" | sed "s/\(\/\+\)$//g" | awk -F/ '{print $NF}'`
	bklog "[!] Running killkali to make sure no kali service or process is being run." && killkali
	bklog "[!] Creating chroot backup $target_dir to $2" && cd $1/../ && busybox tar czf $2 $target_dir
	;;
*)
	echo "[!] Usage: chroot_backup <full_path_of_your_chroot_folder> <full_path_with_desired_name.tar.gz>"
	echo "[!] For example: chroot_backup /data/local/nhsystem/kali_armhf /sdcard/kalifs-backup.tar.gz"
	;;
esac
