#!/system/bin/sh

if [ -x /system/xbin/busybox_nh ]; then
	busybox=/system/xbin/busybox_nh
elif [ -x /sbin/busybox_nh ]; then
	busybox=/sbin/busybox_nh
elif [ -x /system/xbin/busybox ]; then
	busybox=/system/xbin/busybox
elif [ -x /data/local/bin/busybox ]; then
	busybox=/data/local/bin/busybox
elif [ -x /system/bin/busybox ]; then
	busybox=/system/bin/busybox
elif [ -x /su/bin/busybox ]; then
	busybox=/su/bin/busybox
elif [ -x /data/adb/magisk/busybox ]; then
	busybox=/data/adb/magisk/busybox
elif [ -x /sbin/busybox ]; then
	busybox=/sbin/busybox
elif [ -x /sbin/.magisk/busybox/busybox ]; then
	busybox=/sbin/.magisk/busybox/busybox
else
	echo "Busybox not found!  Install it, dummy!"
	log "Busybox not found!  Install it, dummy!"
	exit
fi

export bin=/system/bin
export mnt=/data/local/nhsystem/kali-armhf
PRESERVED_PATH=$PATH
export PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH
export TERM=linux
export HOME=/root
export LOGNAME=root
export chroot_image=/sdcard/kali-chroot.img
unset LD_PRELOAD

kill_pids() {
    local lsof_full=$(lsof | awk '{print $1}' | grep -c '^lsof')
    if [ "${lsof_full}" -eq 0 ]; then
        local pids=$(lsof | grep "$mnt" | awk '{print $1}' | uniq)
    else
        local pids=$(lsof | grep "$mnt" | awk '{print $2}' | uniq)
    fi
    if [ -n "${pids}" ]; then
        kill -9 ${pids} 2> /dev/null
        return $?
    fi
    return 0
}

########## Shutdown kali service ##########
## set shmmax to 128mb to free memory ##

$busybox sysctl -w kernel.shmmax=134217728
$busybox chmod 666 /dev/null

echo "Shutting down SSH Server"
$busybox chroot $mnt /etc/init.d/ssh stop > /dev/null 2>&1

echo "Shutting down Postgresql"
$busybox chroot $mnt /etc/init.d/postgresql stop > /dev/null 2>&1

echo "Shutting down Vncserver"
pkill Xtightvnc
rm -f $mnt/root/.vnc/*.log *.pid > /dev/null 2>&1
rm -f $mnt/tmp/.X*-.lock .X*-unix/* > /dev/null 2>&1

########## Kill all running kali terminals first ##########
echo " [!] Killing all running kali terminals.."
kill_pids

########## unmount everything ##########
echo " [!] Removing all Kali mounts.."
if [ -d "$mnt/dev/shm" ]; then
    $busybox umount $mnt/dev/shm 2> /dev/null && echo "umounted shm"
fi

if [ -d "$mnt/dev/pts" ]; then
    $busybox umount $mnt/dev/pts 2> /dev/null && echo "umounted pts"
fi

if [ -d "$mnt/dev" ]; then
    [ -e "$mnt/dev/null" ] && rm $mnt/dev/null
    $busybox umount $mnt/dev 2> /dev/null && echo "umounted dev"
    rmdir $mnt/dev
fi

if [ -d "$mnt/proc" ]; then
    $busybox umount $mnt/proc 2> /dev/null && echo "umounted proc"
    rmdir $mnt/proc
fi

if [ -d "$mnt/sys" ]; then
    $busybox umount $mnt/sys 2> /dev/null && echo "umounted sys"
    rmdir $mnt/sys
fi

if [ -d "$mnt/sdcard" ]; then
    $busybox umount $mnt/sdcard 2> /dev/null && echo "umounted sdcard"
    rmdir $mnt/sdcard
fi

if [ -d "$mnt/external_sd" ]; then
    $busybox umount $mnt/external_sd 2> /dev/null && echo "umounted external_sd"
    rmdir $mnt/external_sd
fi

if [ -d "$mnt/mnt/usbdisk" ]; then
    $busybox umount $mnt/mnt/usbdisk 2> /dev/null && echo "umounted /mnt/usbdisk"
    rmdir $mnt/mnt/usbdisk
fi

if [ -d "$mnt/mnt" ]; then
    $busybox umount $mnt/mnt 2> /dev/null && echo "umounted /mnt/usbdisk"
    rmdir $mnt/mnt
fi

###### umount the chroot as well if it is being mounted. Here the directory method will not be affected. ######
if [ "$(losetup -a | grep $chroot_image)" ]; then
    if [ "$($busybox umount $mnt 2>&1 > /dev/null)" ]; then
        echo " [-] Unable to umount the kali chroot image."
        echo " [!] If so, please try to close all the kali terminals first, secondly manually umount all the mointpoints on kali chroot, and lastly kill all the running services like ssh, vnc, webservice etc..."
    else
        echo "umounted kali-armhf"
    fi
fi

# Run e2fsck everytime we umount the kali chroot image on enrypted device.
if [ -f "$chroot_image" ]; then
    echo " [!] Running e2fsck to check image $chroot_image.."
    e2fsck -y $chroot_image
fi

# Check again if chroot image is really umounted.
if [ "$(losetup -a | grep $chroot_image)" ]; then
    echo " [!] $mnt is still being mounted. Something is wrong!" && read
fi

export PATH=$PRESERVED_PATH