#!/system/bin/sh

if [ -x /system/xbin/busybox_nh ]; then
	busybox=/system/xbin/busybox_nh
elif [ -x /sbin/busybox_nh ]; then
	busybox=/sbin/busybox_nh
elif [ -x /system/xbin/busybox ]; then
	busybox=/system/xbin/busybox
elif [ -x /data/local/bin/busybox ]; then
	busybox=/data/local/bin/busybox
elif [ -x /system/bin/busybox ]; then
	busybox=/system/bin/busybox
elif [ -x /su/bin/busybox ]; then
	busybox=/su/bin/busybox
else
	echo "Busybox not found!  Install it, dummy!"
	log "Busybox not found!  Install it, dummy!"
	exit
fi

export bin=/system/bin
export mnt=/data/local/nhsystem/kali-armhf
PRESERVED_PATH=$PATH
export PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH
export TERM=linux
export HOME=/root
export LOGNAME=root
unset LD_PRELOAD

# set shmmax to 128mb to free memory#

$busybox sysctl -w kernel.shmmax=134217728

echo "Shutting down SSH Server"
$busybox chmod 666 /dev/null

$busybox chroot $mnt /etc/init.d/ssh stop

echo "Shutting down Postgresql"
$busybox chroot $mnt /etc/init.d/postgresql stop

# unmount everything

echo "Removing all Kali mounts"
$busybox umount $mnt/dev/shm && echo "unmounted shm"
$busybox umount $mnt/dev/pts && echo "unmounted pts"
$busybox umount $mnt/dev && echo "unmounted dev"
$busybox umount $mnt/proc && echo "unmounted proc"
$busybox umount $mnt/sys && echo "unmounted sys"
$busybox umount $mnt/system && echo "unmounted system"
$busybox umount $mnt/sdcard && echo "unmounted $mnt$sdcard"
$busybox umount $mnt/external_sd && echo "unmounted external_sd"

if [ -d "$mnt/dev/shm" ]; then
    rmdir $mnt/dev/shm
fi

if [ -d "$mnt/dev/pts" ]; then
    rmdir $mnt/dev/pts
fi

if [ -d "$mnt/dev" ]; then
    rmdir $mnt/dev
fi

if [ -d "$mnt/proc" ]; then
    rmdir $mnt/proc
fi

if [ -d "$mnt/sys" ]; then
    rmdir $mnt/sys
fi

if [ -d "$mnt/system" ]; then
    rmdir $mnt/system
fi

if [ -d "$mnt/sdcard" ]; then
    rmdir $mnt/sdcard
fi

if [ -d "$mnt/external_sd" ]; then
    rmdir $mnt/external_sd
fi

if [ $($busybox umount $mnt 2>&1 > /dev/null) ]; then
    echo " [-] Unable to umount the kali chroot image."
    echo " [-] Please close all the kali terminals and umount all the mointpoint on kali chroot first then try again."
else
    echo "unmounted kali-armhf"
fi

# Run e2fsck everytime it umount the kali chroot image.
e2fsck -y /sdcard/kali-chroot.img

export PATH=$PRESERVED_PATH