#!/system/bin/sh
#
# @Usage
# ./pine-nano start 172.16.42.245 172.16.42.0/24 172.16.42.1 1471
# ./pine-nano stop
# $1 = start/stop
# $2 = PINEAPPLE_CLIENT_IP
# $3 = PINEAPPLE_CIDR
# $4 = PINEAPPLE_GATEWAY
# $5 = PINEAPPLE_PORT

GATEWAY=$(getprop dhcp.wlan0.gateway)
PINEAPPLE_CLIENT_IP=$2  # 172.16.42.245/24
PINEAPPLE_CIDR=$3       # 172.16.42.0/24
PINEAPPLE_GATEWAY=$4    # 172.16.42.1
PINEAPPLE_PORT=$5       # 1471

ROUTING_TBL=32000

f_start(){
ip addr flush dev eth0
ip addr add $PINEAPPLE_CLIENT_IP dev eth0
ip link set eth0 up
ip rule add prio $ROUTING_TBL from all lookup $ROUTING_TBL
ip route add table $ROUTING_TBL $PINEAPPLE_CIDR dev eth0
ip rule add from $PINEAPPLE_CIDR table $ROUTING_TBL
ip rule add to $PINEAPPLE_CIDR table $ROUTING_TBL
ip route add default via $GATEWAY
ip route add default via 172.16.42.1 dev eth0 table $ROUTING_TBL
sleep 10
am start -a android.intent.action.VIEW -d http://$PINEAPPLE_GATEWAY:$PINEAPPLE_PORT
}

f_stop(){
ip route flush table $ROUTING_TBL
ip addr flush dev eth0
}

if [[ $1 == "start" ]];then
    f_start
fi

if [[ $1 == "stop" ]]; then
    f_stop
fi