#!/system/bin/sh
unset LD_PRELOAD

[ -f /sdcard/nh_files/usb_army.sh ] || {
echo "Please place the 'usb_army.sh' under '/sdcard/nh_files/punkscripts'"
exit 1
}

sh /sdcard/nh_files/punkscripts/usb_army.sh
